# Use python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy current directory into /app container
COPY . /app

# Install packages
RUN pip install flask

# Make port 5000 available outside container
EXPOSE 5000

# Run app.py when container launches
CMD ["python", "app.py"]

